### ISSUE TITLE
feat: add `monitor::from_point()`

### ISSUE THREAD

**Issue by srsholmes** [tauri-apps/tao#187]
Add a method called `monitor::from_point()`.  Apologies I am not 100% sure what this method is for, but it was discussed by @amrbashir in [this thread.](https://github.com/tauri-apps/tauri/issues/2258)

Possibly for allow calculations to position windows between workspaces / monitors.

**Comment by amrbashir** [comment]
yeah this is necessary for apps that want to show itself relative to the screen, for example an overlay music player

They would need to get cursor position first, then get the monitor from it then calculate their window position as they want.

**Comment by CNLHC** [comment]
Do we have any plans to support this feature?
I am willing to contribute something but I am not sure whether the PR is welcomed here or not.

**Comment by amrbashir** [comment]
@CNLHC PRs are always welcome.

**Comment by CNLHC** [comment]
I wrote a draft [PR](https://github.com/tauri-apps/tao/pull/608) that tries to solve this issue. 

Since we already have the `available_monitors` method, a simple way to achieve `monitor::from_point` is by enumerating all the available monitors and returning the monitor that contains the given point.

Besides the `monitor::from_point()` method, this pr also exposes a `monitor_from_point` in the `window` namespace.

Currently, this PR only contains macOS implementation, if any reviewer thinks it is the correct way to solve this problem, I will complete this PR by supporting other platforms : ).
