### ISSUE TITLE
Rename `ReceivedImeText` event to `ReceivedText`

### ISSUE THREAD

**Issue by wusyong** [tauri-apps/tao#249]
Current `ReceivedImeText` only pass the string when users use IME. While we could use key event to receive characters if they are not using IME, it will be a mess if we need to handle both inputs with and without IME.
I believe it's better to get an event that can pass the determined text from OS.

cc @lucasfernog and @amrbashir since this will change a bit on Tauri internally

**Comment by amrbashir** [comment]
I think we should bring back the old keyboard api and stick with it for a while until winit finishes all of the stuff related to the new keyboard api .

**Comment by amrbashir** [comment]
Okay I read through winit's new keyboard api [issue ](https://github.com/rust-windowing/winit/issues/753) and turns out that they indeed removed `ReceivedCharacter` and replaced by `KeyEvent.logical_key`. [more info](https://github.com/rust-windowing/winit/issues/753#issuecomment-723562586)

they also introduced `ReceivedImeText` but it is temporary and will be replaced with [`CompositionEvents`](https://github.com/rust-windowing/winit/issues/1497) but that is still an unfinished api so we use `ReceivedImeText` until it is finished.

**Comment by lucasfernog** [comment]
IIRC tauri doesn't even expose the keyboard APIs right now.
