### ISSUE TITLE
inconsistent behavior across platforms

### ISSUE THREAD

**Issue by wtholliday** [tauri-apps/tao#343]
I'm noticing inconsistent results when using tao across macOS, windows and linux.

To reproduce, clone https://github.com/audulus/rui and check out f92d301

run: `cargo run --example menu`

on macOS: menu works as expected
on Windows: menu doesn't appear (perhaps the menu is obscured by the wgpu viewport. tao's custom_menu example does work)
on Linux: entire view is obscured (was working when using winit)

**Comment by amrbashir** [comment]
On Linux, tao uses gtk so it can't work with wgpu, unless they support it explicitly. tao on Linux is not compatible with winit.

**Comment by wtholliday** [comment]
Ok that explains Linux then, what about Windows?

**Comment by amrbashir** [comment]
I haven't used wgpu myself and I don't know how it draws to the window on Windows so I'll have to check this myself but I am currently away for 3 weeks. I will mark this as "needs investigation" and hopefully someone can investigate it before me.

**Comment by amrbashir** [comment]
Unfortunately I can't investigate this at all, the system I have right now, only supports DX11 and `wgpu` doesn't support DX11 yet. Can you share some screenshots? It might help me spot the issue.

**Comment by amrbashir** [comment]
My bad I guess, I was looking at the supported platforms table in the README, maybe they haven't updated it yet. It turned out anyway, that my system supports DX12, I was missing a driver update but I still encounter issues with `wpgu` examples and still unable to run them. I won't turn this issues into a `wgpu` triage issue so if anyone could just provide a screenshot of the bug, I may have an idea of what is going on.

**Comment by amrbashir** [comment]
hey, @wtholliday. It is been a while but I finally managed to run your menu example. And here is what I found:
I thought WGPU might be blocking the menu but I made a quick c++ script that injected a menu to the rui window and it worked, I can see the menu then I checked your crate code and found out that you're using `Window::set_menu` to set the menu which is not supported on Windows see https://docs.rs/tao/latest/tao/window/struct.Window.html#method.set_menu .

Menus will be extracted in its own crate so you don't need to depend on tao at all, I already started working on them here https://github.com/amrbashir/muda, All features of tao menu is implemented there now so you could use it but I plan to do a rewrite for it because it had limitations which made it impossible to implement Localized Lables. see https://github.com/amrbashir/muda/issues/5
