### ISSUE TITLE
[feat] Read dark/light theme on MacOS and Linux

### ISSUE THREAD

**Issue by kkoomen** [tauri-apps/tao#387]
**Describe the problem**

Currently, the API can only read out the current system theme on Windows, but not on MacOS.

The following code below will result in `light` even though I'm in dark mode.

```js
import { appWindow } from '@tauri-apps/api/window';

appWindow.theme().then((theme) => {
  console.log(theme); // returns 'light' even though I'm in dark mode
});
```

**Describe the solution you'd like**

This should work on MacOS as well.

**Alternatives considered**

None.

**Additional context**

N/A

**Comment by keiya01** [comment]
https://indiestack.com/2018/10/dark-mode-series-introduction/
I think this is useful but I could not find some property in objc.

**Comment by keiya01** [comment]
This issue is resolved on macOS, but Linux has still this issue.

**Comment by Layendan** [comment]
Currently using Tao 0.11.2, Tauri 1.0.0, and MacOS 12.4.

Tested with your example using async/await instead of .then() and it did not work. It returned "light" no matter what system appearance I used. Using the provided "tauri://theme-changed" event listener DID return the correct appearance setting though.

Tested on two different MacBooks (M1 and x86) both resulted in the same problem.

**Comment by lucasfernog** [comment]
@Layendan support on Tauri will be available in the next release (either tomorrow or wednesday).
