### ISSUE TITLE
[bug] "Enter fullscreen" doesn't change display name while in fullscreen

### ISSUE THREAD

**Issue by kotx** [tauri-apps/tao#391]
### Describe the bug

This is fine:
<img width="213" alt="image" src="https://user-images.githubusercontent.com/33439542/167320342-2996380f-d6f6-4bea-b6c4-4c64cfcbcb7f.png">

But after I enter fullscreen:
<img width="210" alt="image" src="https://user-images.githubusercontent.com/33439542/167320350-81852601-56e4-44cc-95c9-0251fa9668f1.png">

### Reproduction

```rs
let view_menu = Menu::new().add_native_item(MenuItem::EnterFullScreen);
let menu = Menu::new().add_submenu(view_menu);
tauri::Builder::default().menu(menu)
// ...
```

### Expected behavior

Menu item changes to "Exit fullscreen". Alternatively we can have the menu item just show "Fullscreen", optionally with a checkbox to show the state, like VSCode:
<img width="265" alt="image" src="https://user-images.githubusercontent.com/33439542/167320422-e396de0c-6302-4b31-b5e4-9465bee8557c.png">

### Platform and versions

```shell
Environment
  › OS: Mac OS 12.3.1 X64
  › Node.js: 16.14.2
  › npm: 8.5.0
  › pnpm: 6.11.0
  › yarn: 1.22.15
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.10
  › @tauri-apps/api [NPM]: 1.0.0-rc.5
  › tauri [RUST]: 1.0.0-rc.9,
  › tauri-build [RUST]: 1.0.0-rc.8,
  › tao [RUST]: 0.8.4,
  › wry [RUST]: 0.16.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ src-tauri
  └─ src
```

**Comment by keiya01** [comment]
I think this issue is related to https://github.com/tauri-apps/tao. But to redraw title we need to change current process.
As the easy way, we can also change default title in the following code. hmm..
https://github.com/tauri-apps/tao/blob/b7e41fe59c4d9995b013aa61210525182ce04435/src/platform_impl/macos/menu.rs#L222

**Comment by wusyong** [comment]
Maybe we can rename to "Toggle Full Screen" just for easy fix.

**Comment by biztos** [comment]
In case anybody is still watching this, I have exactly this same problem in 2025 with Tauri 2.0.

The file that was fixed above has since been removed.  My best guess is that this should be handled in `tao/src/platform_impl/macos/window_delegate.rs` around line 573 where `window_did_enter_fullscreen` is managed.

However, I am a Tauri Noob, so I'm not reopening the bug: it could be that I'm holding it wrong.

**Comment by FabianLars** [comment]
@biztos tao does not handle menu items anymore. When i check a new create-tauri-app project it also shows `Toggle Full Screen` for me. Can you open an issue in the tauri repository with the output of the `tauri info` command, a screenshot, and the code of the menu if you're not using the built-in default one.

**Comment by biztos** [comment]
Thanks for the reply.  I just did a fresh new app and indeed, by default it's `Toggle Full Screen` and working as expected with the default menu.

When I have time I will dig into my custom menu setup and try to find out what's wrong and whether it's issue-worthy.

In case you're curious, I am currently using a hackaround in which I name the menu `View ` (with trailing space) and the system doesn't add the non-updating menu item, allowing me to handle the custom one correctly.  If I simply rename it `View` (no trailing space) then it adds the item back in.  I would prefer the default behavior from the fresh app, because I haven't figured out how to use the 🌐 modifier in my custom menu.  But I have a growing list of other items I will need to have in `View` so I have to customize it.

```rust
// Trailing space on View prevents macOS adding "Enter Full Screen,"
// which we can't have b/c it doesn't change to "Exit" when in FS, which
// it doesn't because Tauri doesn't use the native function, which it
// doesn't because (apparently) that would mess with Tauri's worldview of
// its windows. From what I've read online, which might not be true.
let view_menu = SubmenuBuilder::new(app, "View ")
    .id("menu_view")
    .item(&dark_mode)
    .separator()
    .item(&toggle_fullscreen)
    .build()?;
```

Again, thank you for your reply, it was enlightening.

**Comment by FabianLars** [comment]
Were you using a custom menu before as well? That'd probably explain it. In a default app we inject that item ourselves which seemingly prevents the system from injecting its own version. You can do the same if you use the [predefined Fullscreen item](https://docs.rs/tauri/latest/tauri/menu/struct.PredefinedMenuItem.html#method.fullscreen) - if that's not the issue then i'm lost...

**Comment by biztos** [comment]
Yes, and I have confirmed the predefined one works as well.  Thanks for the assistance.
