### ISSUE TITLE
Request: use standardized keyboard types crate

### ISSUE THREAD

**Issue by jkelleyrtp** [tauri-apps/tao#460]
I'm not sure why, but the Tao codebase has a copy of the `keyboard_types::key` enum. I'm building a library that uses the actual `keyboard_types` library and these two enums don't interoperate with each other.

It would be great if Key and Code were taken from a an upstream library so the ecosystem could mesh together better.

**Comment by amrbashir** [comment]
I think the keyboard types used in tao was a merge of the [`new-keyboard`](https://github.com/rust-windowing/winit/tree/new-keyboard) branch in the upstream crate `winit`.

Anyhow, We are gonna eventually revert back to depend on winit directly so this issue might be better suited to be discussed with the winit team.

**Comment by amrbashir** [comment]
`accelerator` module is now rewritten using `keyboard_types` crate in https://github.com/amrbashir/muda/pull/17 (it will take a while though until it lands in the tauri stack)

`global_shortcut` module is going to be removed completely and users will need to build their own shortcut manager on top of `DeviceEvent::Key` 

Only keyboard events are left but since we are planning to move back to use `winit` directly, it is useless to port keyboard events in tao to `keyboard_types` crate. I opened an issue at winit https://github.com/rust-windowing/winit/issues/2394.
