### ISSUE TITLE
[Feature request] EventLoop::run which doesn't terminate the entire program.

### ISSUE THREAD

**Issue by kayabaNerve** [tauri-apps/tao#54]
There is a run_return internally, yet not one publicly exposed. Use case is closing the GUI to prevent further interaction while still enabling backend operations such as DB flushes, not to mention control over the error code.

**Comment by wusyong** [comment]
The signature of this run_return is different from other platforms. It has to consume itself because lots of gtk/glib type methods also need to consume themselves.

The Application will be terminated when the control flow is set to `Exit`. So in practice, users could still close all GUI and still able to run the DB behind the scene.

**Comment by kayabaNerve** [comment]
Closed after learning over Discord you can close a window via dropping the variable.
