### ISSUE TITLE
Add an option --features wayland or features x11

### ISSUE THREAD

**Issue by mikekreuzer** [tauri-apps/tao#568]
Feature request, please. :smiley:

First brought up in relation to #566 (closed), here: [#566](https://github.com/tauri-apps/tao/issues/566#issuecomment-1256123779)

Inspiration is the bevy game engine, their pull request's: [#249](https://github.com/bevyengine/bevy/pull/249)

Motivation is Wayland on Linux seemingly not being able to position windows.

**Comment by FabianLars** [comment]
As Amr said in that other issue: This doesn't make sense for tao since we replaced the custom x11 and Wayland backends with GTK (because we need that for webkitgtk).

Even if we ignore that, this would not necessarily help you. Even if you choose (only) the x11 backend you have no guarantee that XWayland behaves like you want, but it gets even worse: you can't expect XWayland to exist on all Wayland systems in which case it would just crash.

**Comment by amrbashir** [comment]
Apparantly you can force x11 using `GDK_BACKEND` env var, see https://wiki.archlinux.org/title/GTK#Xorg_backend

**Comment by FabianLars** [comment]
We do that in the appimage because it crashes otherwise. Idk but the flag feels a little weird at times too, and it seems to be ignored sometimes for whatever reason (could have been caused by something else, i noticed that when I tested some other appimage stuff)
Aaand it doesn't help with the linked issue either iirc

**Comment by mikekreuzer** [comment]
Thank you both for taking the time to respond, I appreciate it.
