### ISSUE TITLE
Send + Sync is not implemented for iOS proxy

### ISSUE THREAD

**Issue by jkelleyrtp** [tauri-apps/tao#656]
On mac, windows, and linux, the proxy type has an unsafe impl so the proxy can be shared across threads

```rust

pub struct Proxy<T> {
  sender: Sender<T>,
  source: CFRunLoopSourceRef,
}

unsafe impl<T: Send> Send for Proxy<T> {}
unsafe impl<T: Send> Sync for Proxy<T> {}

```

But this does not exist for iOS.

I have to hack around this limitation by doing these impls myself. It'd be great if this was just built in.

**Comment by amrbashir** [comment]
I think it is probably safe to implement `Sync` for it but I am not sure since I can't test it, however, `Send` is implemented for the proxy on iOS
https://github.com/tauri-apps/tao/blob/b3aa3982d18a1ca2c8f08a135d7256b1aca46369/src/platform_impl/ios/event_loop.rs#L164-L169

Shouldn't that be enough? like you can create a new proxy and just send it to the thread instead of sending a reference.
