### ISSUE TITLE
Question & Suggestion: Is it necessary to use `&str` instead of `char` in `tao::keyboard::Key::Character`?

### ISSUE THREAD

**Issue by ruza-net** [tauri-apps/tao#684]
**Is your feature request related to a problem? Please describe.**
I'm contributing to a GUI library that uses `tao` as a dependency. It would seem logical from my point of view to receive `char`-s as keypress events instead of `&str`-s. It's also more ergonomic in applications (e.g. easier to process while pattern-matching events).

**Describe the solution you'd like**
I'm primarily seeking the rationale behind this design decision. Ideally though, I'd like `tao::keyboard::Key::Character` to take `char` instead of `&str`.

**Describe alternatives you've considered**
I can just work with `&str`-s in all applications that use `tao` as a transitive dependency, possibly increasing their complexity.

**Would you want to assign yourself to implement this feature?**
- [ ] Yes
- [x] No

**Additional context**
None.

**Comment by FabianLars** [comment]
So i'm not an expert here but the way i understand it `Key` is the _actual_ input, including more special characters like `é`. Rust's `char` type is a unicode scalar value and not all values, like the aforementioned `é`, are a _single_ unicode scalar point.
In other words this won't compile: `let c = 'é';` but this is fine: `let c = "é";`

**Comment by ruza-net** [comment]
Ok, I see. However, many of the special characters (I've tested Latin, Cyrillic, Glagolitic and Hangul) have normalized forms that fit in a `char` just fine, even with diacritical marks. At least with Latin diacritical marks, modern keyboards produce the normalized forms (including for `é`, which has the normalized form `é`). For these, it takes deliberate effort to produce an actual pair of a base character and a combining one.

I'm not familiar with input from other (esp. non-European) languages. Does the case with combined characters actually come up in practice?

**Comment by FabianLars** [comment]
> modern keyboards produce the normalized forms (including for é, which has the normalized form é)

ah yeah true, mixed something up, sry... but then `modern keyboards` raises the question if that's _always_ the case 🤔 

> I'm not familiar with input from other (esp. non-European) languages. Does the case with combined characters actually come up in practice?

Well, as i said i'm not an expert on that topic at all (you likely know much more than me), but there should be a reason that tao, this crate https://crates.io/crates/keyboard_types, and [winit](https://togithub.com/rust-windowing/winit/pull/2662) opt for a string right? (at least i hope there's a reason lol)

Or maybe it's because the `Key` enum is not only used for (receiving) events?

welp, enough of the wild guesses, i take back my initial comment and leave this topic to someone who actually knows their stuff 😂

**Comment by amrbashir** [comment]
We are moving towards switching back to winit so there is no point in trying to change this here. I think this is better suited to be discussed here https://github.com/pyfisch/keyboard-types/issues/19
