### ISSUE TITLE
Problem with Tao with pixels under Linux

### ISSUE THREAD

**Issue by markusmoenig** [tauri-apps/tao#717]

**Comment by markusmoenig** [comment]
The minimum Tao example in pixels (https://github.com/parasyte/pixels) does not work under Linux. The pixels buffer overwrites the window title and frame which causes a lot of flicker and events do not work. 

The author said Tao allocates space for the menu bar under Windows and macOS but not under Linux.

**Comment by amrbashir** [comment]
It works fine on my Linux, Manjaro (KDE) and we do allocate space for the menu bar on Linux too, it will have 0px height unless you add a menu and then you will see it.

https://user-images.githubusercontent.com/48618675/232546707-ae57cd38-d0ab-4490-b904-59d84d6fe408.mp4

We need more info about your system and maybe a recording of the issue

**Comment by markusmoenig** [comment]
I just tried again on my Fujitsu laptop with Ubuntu 20.04:

The pixels "minimal-winit" example works fine with a window border etc.

The pixels "minimal-tao" example (which by default uses version 0.17 of tao) gives an error message: "drawable is not a native x11 window", "surface configuration failed".

After switching to 0.19 of tao it runs, but overwrites the window borders, i.e. you see only the content of the window without any system window frame at all.

I assume I use some crappy default display driver. Note, I have no idea about Linux, I just use the laptop to build binaries for my apps.

I just raised this issue because winit works fine on my system (whatever the version).

Let me know if you need anything else or if the issue is of interest at all.

**Comment by amrbashir** [comment]
From the error above, it looks like you are on Wayland and I think there was another issue about missing decorations on wayland, could you confirm that you're indeed on Wayland? and by border do you mean the titlebar that contains the close, minimize and maximize button as well as the border that goes around the window?

**Comment by markusmoenig** [comment]
Yes, Wayland on a vanilla Ubuntu 20.04.

**Comment by amrbashir** [comment]
Thanks for confirming, so the reason why winit works well, is because they're using raw wayland APIs while tao uses gtk which has its own abstractions above wayland APIs, I am not sure if we can fix this in our code or wait for gtk to fix it, but unfortunately none of the devs here use wayland as main driver and it may take a while to be fixed so I will flag this as a low priority.

**Comment by parasyte** [comment]
> It works fine on my Linux, Manjaro (KDE) and we do allocate space for the menu bar on Linux too, it will have 0px height unless you add a menu and then you will see it.

FWIW, the behavior shown in your video is not what is expected! The window is supposed to have a menu bar with a single "File" menu and an "Exit" menu item. Instead, you have the inner contents being drawn over top of it. In fact, the last frame of the video shows the menu bar with an empty window. (Here's a screenshot from the video...)

![image](https://user-images.githubusercontent.com/456942/232951389-da6d13b2-f545-4397-bbbe-839b3fcabc4d.png)

For comparison, here is the same example on Windows 11:

![image](https://user-images.githubusercontent.com/456942/232951661-619a4f34-4ba8-424f-95cc-d90b14769ecb.png)

**Comment by amrbashir** [comment]
@parasyte The menu on Windows is a native control that is rendered outside the client area by Windows so you can't render over it, however on Linux, GTK renders all of its widgets in the client area of the x11 window and since the GTK Menu is just a widget, it will be drawn inside the client area of the x11 window and when you render on to the x11 window using open-gl or similar tech using the raw window handle, it will render on top of the GTK Menu. I am not sure if there is a way around this tbh, but maybe you could see if the Menu [`is_visible`](https://docs.rs/tao/latest/tao/window/struct.Window.html#method.is_menu_visible) and don't render in the first few pixels. 

I will close this since we can't do anything about this situation unfortunately.

**Comment by parasyte** [comment]
Does this mean that "menus behave the same, regardless of platform" is out of scope for `tao`?

It looks like the only way to get this behavior is using GTK on every platform. At which point you may as well use GTK menus instead of the native menus provided by `tao`.

> I am not sure if there is a way around this tbh, but maybe you could see if the Menu [`is_visible`](https://docs.rs/tao/latest/tao/window/struct.Window.html#method.is_menu_visible) and don't render in the first few pixels.

It's more than that. The window needs to be resized to account for the height of the menubar in addition to offsetting the draw location. The precise size of the menubar needs to be exposed in some way. Or else the client needs to make a best guess and hope the menubar renders with the same size on every platform with every theme and every font size.

----

The recommended way to do this with GTK looks like `GdkVulkanContext`... But `tao` is using GTK 3, so that isn't even an option. The GTK 3 menubar implementation is just fundamentally incompatible with Vulkan. GTK 3 has `GtkGLArea` if you want to use OpenGL _and_ write client-side glue to integrate with GTK 3 properly. (Which is another way of saying "just use GTK 3 on every platform.")

The whole situation just seems dire for `tao::menu::MenuBar`.

**Comment by amrbashir** [comment]
> Does this mean that "menus behave the same, regardless of platform" is out of scope for tao?

Tao is kinda of on maintenance mode for now as we are investigating switching back to winit and are extracting the major features of tao into its own crates, such as menus have been extracted to its own crate https://github.com/tauri-apps/muda btw, which exposes the `GtkMenu` and could potentioally also expose the `GtkMenuBar`. There is also the `muda` branch that has everything stipped from `tao` and works well with the new crates.

Unfortunately, the linux ecosystem with its million window managers doesn't seem to have a protocol/spec for creating a window menu that is outside the client area so usually all apps or frameworks like GTK will draw the menu on its own.
