### ISSUE TITLE
Can we re-export the shortcut types on iOS even if they don't do anything?

### ISSUE THREAD

**Issue by jkelleyrtp** [tauri-apps/tao#754]
**Is your feature request related to a problem? Please describe.**
iOS doesn't support global shortcuts, so it means any app depending on the Shortcut types has to manually stub things out.

**Describe the solution you'd like**
It'd be great if we could add support for global shortcuts on iOS or just simply stub them out in the short term.

**Would you want to assign yourself to implement this feature?**
- [ ] Yes
- [ ] No
- [x] I'd be happy to but it might be easier for a tauri engineer.

**Comment by amrbashir** [comment]
This was by design, since these platforms don't support global shortcuts at all so any usage of these types should be guarded by `#[cfg(any(windows, target_os = "macOS", target_os = "Linux")]`, not sure why an app would need to stub them out?

Also I should note that the shortcuts implementation in this repo is on maintenance mode, and have been moved into https://github.com/tauri-apps/global-hotkey but

**Comment by amrbashir** [comment]
Closing as global shortcut APIs and related types have been removed from tao for quite some time now.
